import DashboardCard from "../components/DashboardCard";
import report from "../Data/report";
import "../Css/reports.css";
function Report(){
    return(

    <div className="reports">
            <div className="reports-header">
                <h2>Reports</h2>
            </div>
            <p>Construction reports and performance analytics</p>

      
        <div className="report-top">
            <input type="text" placeholder="search" />
            <button>Generate Report</button>
        </div>
        <div className="report-cards">
           <DashboardCard title="Total Reports" value="36" icon="📄"/>
           <DashboardCard title="Completed Reports" value="28" icon="📄"/>
           <DashboardCard title="Pending Reports" value="8" icon="📄"/>
           <DashboardCard title="Report Accuracy" value="98%" icon="📄"/>
        </div>
        <div className="report-overview">
            <h3>Project Completion Overview</h3>
            <div className="project-progress">
                <h4>Mall Build</h4>
                <div className="progress-bar">
                   <div className="progress-fill"></div>
                </div>
                
            </div>
            <span>80%</span>

        </div>
        <div className="project-progress">
            <h4>Hospital</h4>
            <div className="progress-bar">
                <div className="progress-fill"></div>
            </div>
            <span>60%</span>

        </div>
        <div className="project-progress">
            <h4>Bridge</h4>
            <div className="progress-bar">
                <div className="progress-fill"></div>
            </div>
            <span>40%</span>

        </div>
        <div className="report-table-box">
            <table>
                <thead>
                 <tr>
                    <th>Report ID</th>
                    <th>Project</th>
                    <th>Type</th>
                    <th>Generated By</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Action</th>
                 </tr>
                </thead>
                <tbody>{report.map((x,index)=><tr key={index}>
                    <td>{x.ReportID}</td>
                    <td>{x.Project}</td>
                    <td>{x.Type}</td>
                    <td>{x.GeneratedBy}</td>
                    <td>{x.Date}</td>
                    <td>{x.Status}</td>
                    <td>{x.Action}</td>
                </tr>)}
                </tbody>
            </table>

        </div>

      </div>
    );
}
export default Report;
