import React from 'react';
import { useReportsController } from '../controllers/useReportsController';
import { PageHeader, FilterBar, Badge, ProgressBar, Card } from '../components/ui';
import DashboardCard from "../components/DashboardCard";
import { FiFileText, FiCheckSquare, FiClock, FiPieChart, FiZap, FiDownload } from 'react-icons/fi';

function Reports() {
    const {
        searchTerm,
        setSearchTerm,
        allReports,
        filteredReports,
        getStatusVariant,
        handleGenerateReport
    } = useReportsController();

    return (
        <div className="space-y-6">
            <PageHeader
                title="Reports & Analytics"
                description="Construction audit logs, safety reports, and performance analytics."
                actionLabel="Generate New Report"
                actionIcon={FiZap}
                onActionClick={handleGenerateReport}
            />

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
                <DashboardCard title="Total Reports" value="36" icon={FiFileText} trend="+6 this month" />
                <DashboardCard title="Completed Reports" value="28" icon={FiCheckSquare} trend="77% finalized" />
                <DashboardCard title="Pending Review" value="8" icon={FiClock} trend="In review" />
                <DashboardCard title="Report Accuracy" value="98%" icon={FiPieChart} trend="High confidence" />
            </div>

            <Card hover={false} className="space-y-4">
                <h3 className="text-lg font-bold text-slate-100 mb-1">Project Milestone Overview</h3>
                <div className="space-y-3">
                    <div>
                        <div className="flex justify-between text-xs font-semibold mb-1">
                            <span className="text-slate-200">Mall Build Milestone</span>
                            <span className="text-blue-400 font-mono">80%</span>
                        </div>
                        <ProgressBar progress={80} showLabel={false} variant="blue" />
                    </div>
                    <div>
                        <div className="flex justify-between text-xs font-semibold mb-1">
                            <span className="text-slate-200">Hospital Site Construction</span>
                            <span className="text-indigo-400 font-mono">60%</span>
                        </div>
                        <ProgressBar progress={60} showLabel={false} variant="indigo" />
                    </div>
                    <div>
                        <div className="flex justify-between text-xs font-semibold mb-1">
                            <span className="text-slate-200">Flyover Bridge Support Structure</span>
                            <span className="text-emerald-400 font-mono">40%</span>
                        </div>
                        <ProgressBar progress={40} showLabel={false} variant="emerald" />
                    </div>
                </div>
            </Card>

            <FilterBar
                searchTerm={searchTerm}
                onSearchChange={setSearchTerm}
                placeholder="Search report ID, project, type, or author..."
                filteredCount={filteredReports.length}
                totalCount={allReports.length}
                itemLabel="audit reports"
            />

            <Card className="overflow-hidden p-0" hover={false}>
                <div className="overflow-x-auto">
                    <table className="w-full text-left text-sm border-collapse">
                        <thead>
                            <tr className="border-b border-slate-800 text-xs font-semibold uppercase tracking-wider text-slate-400 bg-slate-800/40">
                                <th className="py-3.5 px-5">Report ID</th>
                                <th className="py-3.5 px-5">Project Name</th>
                                <th className="py-3.5 px-5">Report Type</th>
                                <th className="py-3.5 px-5">Generated By</th>
                                <th className="py-3.5 px-5">Date</th>
                                <th className="py-3.5 px-5">Status</th>
                                <th className="py-3.5 px-5 text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-800/60 text-slate-300">
                            {filteredReports.map((x, index) => (
                                <tr key={index} className="hover:bg-slate-800/40 transition-colors">
                                    <td className="py-3.5 px-5 font-mono text-xs font-bold text-blue-400">#{x.ReportID}</td>
                                    <td className="py-3.5 px-5 font-semibold text-slate-100">{x.Project}</td>
                                    <td className="py-3.5 px-5 text-slate-300">{x.Type}</td>
                                    <td className="py-3.5 px-5 text-slate-400">{x.GeneratedBy}</td>
                                    <td className="py-3.5 px-5 font-mono text-xs text-slate-400">{x.Date}</td>
                                    <td className="py-3.5 px-5">
                                        <Badge variant={getStatusVariant(x.Status)}>
                                            {x.Status}
                                        </Badge>
                                    </td>
                                    <td className="py-3.5 px-5 text-right">
                                        <button className="inline-flex items-center gap-1.5 text-xs font-semibold text-blue-400 hover:text-blue-300 bg-blue-500/10 hover:bg-blue-500/20 px-3 py-1.5 rounded-lg border border-blue-500/20 transition-all">
                                            <FiDownload className="text-sm" />
                                            <span>{x.Action || "Download"}</span>
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </Card>
        </div>
    );
}

export default Reports;